### ISSUE TITLE
account creation broken

### ISSUE THREAD

**Issue by Gishi1** [Anathena/Anathena#198]
i tried to make an account butt it keeps saying the password dose not match when it dose.

ummmmm... also when will the pointer scanner be working?

**Comment by zcanann** [comment]
I'll get a fix out tonight, thanks for bringing this to my attention

Pointer scanner is a fairly high priority right now, so hopefully I can get something out within a few weeks or a month.

**Comment by zcanann** [comment]
Should be resolved
