### ISSUE TITLE
Open process by PID / Open Windows Store process

### ISSUE THREAD

**Issue by Rbn3D** [Anathena/Anathena#284]
It's possible to open a process by specifying it's PID?

I'm trying to cheat in a Windows Store game. I can get the PID in task manager, but Squalr list of proccess doesn't seem to show windows store games or their PID.

Is there any way to do this? It's planned to add support for this feature?

Thanks in advance.

**Comment by zcanann** [comment]
Seems reasonable and easy, I can tackle this one soon-ish

**Comment by Rbn3D** [comment]
Well, the process name it's shown (I just found it on the list), Iso I was able to attach it. It's just too hard to find. No alphabetical order and no icon for most process.

Thanks for the quick answer!
