### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Hiro-LordOfAThousandSongs** [Anathena/Anathena#287]
I'm highly curious if this would work on ROBLOX. Reason i ask is because CE (Cheat Engine) no longer works on ROBLOX, so I'm wondering if that's different for this.

**Comment by coffeemesh** [comment]
Very low effort question, please refrain from opening issues on GitHub for such questions, I am sure asking on [Discord](https://discord.com/invite/Pq2msTx) would've been way more effective.
Stay safe.
